<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZqnkZ45\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZqnkZ45/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZqnkZ45.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZqnkZ45\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZqnkZ45\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZqnkZ45',
    'container.build_id' => '726899b8',
    'container.build_time' => 1663156254,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZqnkZ45');
