<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCoK3qQG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCoK3qQG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCoK3qQG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCoK3qQG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCoK3qQG\App_KernelDevDebugContainer([
    'container.build_hash' => 'CoK3qQG',
    'container.build_id' => '01b832d1',
    'container.build_time' => 1663148875,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCoK3qQG');
