<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGCn6GhA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGCn6GhA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGCn6GhA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGCn6GhA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGCn6GhA\App_KernelDevDebugContainer([
    'container.build_hash' => 'GCn6GhA',
    'container.build_id' => 'e6ddffd6',
    'container.build_time' => 1663154923,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGCn6GhA');
